### ISSUE TITLE
Serial Number Stuck at 6 in Attendance Automation

### ISSUE THREAD

**Issue by Viserion-7** [DenyTwice/murali#1]
#### Description:
The Discord bot, used for automating attendance sheets, consistently sets the serial number to 6 after reaching this value. Each appended data entry displays a serial number of 6 instead of incrementing sequentially.

#### Steps to Reproduce:
1. Use the Discord bot command for attendance automation.
2. Observe that the serial number remains stuck at 6 in the appended data.

#### Expected Behavior:
Serial numbers should increment sequentially for each attendance entry, ensuring uniqueness.

#### Actual Behavior:
The serial number consistently appears as 6 for each appended data entry after reaching this value.

**Comment by govindkrishna03** [comment]
Can i fix this??

**Comment by DenyTwice** [comment]
Cool, gave you a branch to work on.

**Comment by DenyTwice** [comment]
Fixed in #5 by @govindkrishna03
