### ISSUE TITLE
Command does not work if the sheet has not been created.

### ISSUE THREAD

**Issue by DenyTwice** [DenyTwice/murali#7]
If there is no sheet ID matching today's date, the command fails and someone has to manually go create a sheet, thus destroying the entire purpose of the bot. 

Proposed solution: Make a new function that creates a sheet for the day and integrate it with the current flow.

**Comment by Wreck-X** [comment]
Ples moi

**Comment by Viserion-7** [comment]
started working on it

**Comment by DenyTwice** [comment]
Fixed in #11 by @Viserion-7.
